########################################################################################################################
# Collector Image
########################################################################################################################


########
FROM golang:1.24-trixie as backendbuild

WORKDIR /go/src/github.com/analogj/scrutiny

COPY . /go/src/github.com/analogj/scrutiny

RUN apt-get update && apt-get install -y file && rm -rf /var/lib/apt/lists/*
RUN make binary-clean binary-collector

########
FROM debian:trixie-slim as runtime
WORKDIR /opt/scrutiny
ENV PATH="/opt/scrutiny/bin:${PATH}"

RUN echo "deb http://deb.debian.org/debian trixie-backports main" > /etc/apt/sources.list.d/backports.list && \
    apt-get update && \
    apt-get install -y cron ca-certificates tzdata && \
    apt-get install -y -t trixie-backports smartmontools && \
    rm -rf /var/lib/apt/lists/* && \
    update-ca-certificates

COPY /docker/entrypoint-collector.sh /entrypoint-collector.sh
COPY /rootfs/etc/cron.d/scrutiny /etc/cron.d/scrutiny
COPY --from=backendbuild /go/src/github.com/analogj/scrutiny/scrutiny-collector-metrics /opt/scrutiny/bin/
RUN chmod +x /opt/scrutiny/bin/scrutiny-collector-metrics && \
    chmod +x /entrypoint-collector.sh && \
    chmod 0644 /etc/cron.d/scrutiny && \
    rm -f /etc/cron.daily/apt /etc/cron.daily/dpkg /etc/cron.daily/passwd

CMD ["/entrypoint-collector.sh"]
